#pragma once
//SIMON
#define SIMON_WALKING_SPEED 0.08f
#define SIMON_JUMP_SPEED_Y 0.4f
#define SIMON_JUMP_DEFLECT_SPEED 0.2f
#define SIMON_GRAVITY			0.001f
#define SIMON_DIE_DEFLECT_SPEED	 0.5f

#define SIMON_STATE_IDLE			0
#define SIMON_IDLE_LEFT				1
#define SIMON_STATE_WALKING_RIGHT	2
#define SIMON_STATE_WALKING_LEFT	3
#define SIMON_STATE_JUMP			4
#define SIMON_STATE_JUMP_LEFT		5
#define SIMON_STATE_ATTACK			6
#define SIMON_STATE_ATTACK_LEFT		7
#define SIMON_STATE_SIT_RIGHT		8
#define SIMON_STATE_SIT_LEFT		9
#define SIMON_STATE_DIE				10
#define SIMON_STATE_DIE_LEFT		11

#define SIMON_STATE_NORMAL      100
#define SIMON_ATTACK_TIME	600	
#define SIMON_STAND_BBOX_WIDTH		18//16
#define SIMON_STAND_BBOX_HEIGHT		32//30

#define SIMON_SITDOWN_BBOX_WIDTH	1
#define SIMON_SITDOWN_BBOX_HEIGHT	1

#define SIMON_WALK_BBOX_WIDTH		28
#define SIMON_WALK_BBOX_HEIGHT		62

#define SIMON_ANI_DIE			
#define SIMON_UNTOUCHABLE_TIME 3000


//ZOMBIE
#define ZOMBIE_WALKING_SPEED 0.05f;

#define ZOMBIE_BBOX_WIDTH 16
#define ZOMBIE_BBOX_HEIGHT 31

#define ZOMBIE_STATE_DIE 200
#define ZOMBIE_STATE_WALKING 100

//BRICK
#define BRICK_BBOX_WIDTH  75
#define BRICK_BBOX_HEIGHT 14

//GAMEOBJECT
#define ID_TEX_BBOX -100

//GAME
#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024

//MAIN
#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"CastleVania"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 200)
#define SCREEN_WIDTH 384
#define SCREEN_HEIGHT 192

#define MAX_FRAME_RATE 100

#define ID_TEX_SIMON 0
#define ID_TEX_SIMON_ATTACK 5
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MAP1	30
#define ID_TORCH 40

#define ROPE_STATE_ATTACK 0
//Torch
#define TORCH_WIDTH 18
#define TORCH_HEIGHT 32